// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ukdcprqhkyyzpowjxlpq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVrZGNwcnFoa3l5enBvd2p4bHBxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0OTgxNjgsImV4cCI6MjA2NTA3NDE2OH0.zJ-3Z5yyffY8WUGsP0b35S0F89BXFH2ST2lpvr5QQjs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);